# Generated by Django 3.2.4 on 2021-10-29 11:21

from django.db import migrations, models
import rest_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor_details',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Advisor_name', models.CharField(default='', max_length=50)),
                ('Advisor_Photo_URL', models.TextField(default=1, max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Book_call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('advisor_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=50, validators=[rest_api.models.validate_password])),
            ],
        ),
    ]
