# Generated by Django 3.2.4 on 2021-10-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20211029_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_call',
            name='time',
            field=models.DateTimeField(blank=True),
        ),
    ]
