# Generated by Django 3.2.4 on 2021-10-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_alter_book_call_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_call',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
